---
title: "Projects"
description: |
  I really enjoy working on (side) projects related to data analysis and visualizations, especially on social and economic issues. I also love trying to make life slightly easier by building tools, such as R packages. Here are my projects
repository_url: null
creative_commons: null
output: distill::distill_article
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
* {
  box-sizing: border-box;
}

/* Float four columns side by side */
.column {
  float: left;
  width: 50%;
  padding: 15px 15px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  padding: 0px;
  text-align: left;
  background-color: white;
}

.card-title {
  font-weight: bold; 
}

.card-date {
  color: #9E9E9E;
}

.card-description {
  color: #757575;
}
```

```{r Card container}
library(htmltools)


create_card <- function(title, 
                        date,
                        description,
                        url,
                        image_source) {
  
  card <- tags$div(
    class = "column",
    tags$div(
      class = "card",
      tags$a(
        href = url,
        target = "_blank",
        tags$img(src = image_source, style = "width:100%"),
        tags$div(class = "card-title", title),
        tags$div(class = "card-date", date),
        tags$div(class = "card-description", description)
      )
    )
  )
  
  return(card)
  
}


# Create the card in chronological order with the most recent project
# placed on top
tags$div(
  
  # Data journalism at The Jakarta Post
  create_card(
    title = "Data journalism at The Jakarta Post",
    date = "Ongoing",
    description = "A GitHub repo containing code and data behind my stories on social and economic issues at The Jakarta Post",
    url = "https://github.com/dzulfiqarfr/jakpost-chart-data",
    image_source = "images/jakpost-chart-data_preview.png"
  ),
  
  # My Dataviz in 2020 ----
  create_card(
    title = "My dataviz in 2020",
    date = "September 2021",
    description = "One scatter plot, one animated scatter plot, one map and one table on industrial park, COVID-19 and well-being",
    url = "posts/2021-09-21-my-data-visualizations-in-2020/index.html",
    image_source = "posts/2021-09-21-my-data-visualizations-in-2020/figures/my-dataviz-in-2020_preview.png"
  ),

  # jakpoststyle ----
  create_card(
    title = "jakpoststyle",
    date = "January 2021",
    description = "An R package to edit Datawrapper chart properties with an unofficial custom theme of The Jakarta Post",
    url = "https://dzulfiqarfr.github.io/jakpoststyle/",
    image_source = "images/jakpoststyle_preview.png"
  ),
  
  # Indonesia EconRecovery ----
  create_card(
    title = "Indonesia EconRecovery",
    date = "November 2020",
    description = "Charts and tables to track Indonesia’s economic recovery from the COVID-19 pandemic",
    url = "https://dzulfiqarfr.github.io/indonesia-recovery-tracker/",
    image_source = "images/ier_preview.png"
  )
  
)
```

